# Generated by Django 5.0.1 on 2024-01-12 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_story_autor_alter_user_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
