# Generated by Django 5.0.1 on 2024-01-12 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/story_images/')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.story')),
            ],
        ),
    ]
