# Generated by Django 5.0.1 on 2024-01-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_storyimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='backgroundImage',
            field=models.ImageField(blank=True, null=True, upload_to='media/backgroundImages/'),
        ),
        migrations.AddField(
            model_name='storyimages',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
