# Generated by Django 5.0.1 on 2024-01-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_story_backgroundimage_storyimages_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyimages',
            name='underText',
            field=models.BooleanField(default=False),
        ),
    ]
