# Generated by Django 5.0.1 on 2024-01-12 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_storyimages_afterchar_storyimages_width'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storyimages',
            old_name='position',
            new_name='side',
        ),
    ]
