# Generated by Django 5.0.1 on 2024-01-16 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_rename_position_storyimages_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyimages',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.story'),
        ),
    ]
